@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2VsQGV4YW1wbGUuY29tIiwiaWF0IjoxNzgzNTQ4NDUwLCJleHAiOjE3ODM1NDkzNTB9.STAsAzCl4OvpCCsn2pEpoVuMQZ1TvzVdGwuZCOdb0U0

### External API posts
GET {{baseUrl}}/api/v1/external/posts
Authorization: Bearer {{accessToken}}
Accept: application/json

### Crear usuario
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Joel",
  "email": "joel@example.com",
  "password": "password123"
}

### Obtener todos los usuarios
GET {{baseUrl}}/api/v1/users
Authorization: Bearer {{accessToken}}
Accept: application/json

### Obtener usuario por id
GET {{baseUrl}}/api/v1/users/1
Authorization: Bearer {{accessToken}}
Accept: application/json
