@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtaXJhbmRhQHllc3Nlcm0uZGV2IiwiaWF0IjoxNzgzNDY2NzI3LCJleHAiOjE3ODM0Njc2Mjd9.i0XPNS0e_L_iSG6zFg575wfYjitVZkpmUtV5J8t1CNY

### Obtener posts externos
GET {{baseUrl}}/api/v1/external/posts
Accept: application/json

### Crear usuario
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Joel",
  "email": "joel@example.com",
  "password": "password123"
}

### Obtener todos los usuarios
GET {{baseUrl}}/api/v1/users
Authorization: Bearer {{accessToken}}
Accept: application/json

### Obtener usuario por id
GET {{baseUrl}}/api/v1/users/1
Authorization: Bearer {{accessToken}}
Accept: application/json
