@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtaXJhbmRhQHllc3Nlcm0uZGV2IiwiaWF0IjoxNzgzNDY3MzQ5LCJleHAiOjE3ODM0NjgyNDl9.Ng8m7VEAj3VnDm1DHHWjTXgrDXHpbtLcjPSC0Wvigzo
@refreshToken = P-BGSqqLIKui5ByvZ9dH-c17oKitImaioT56Pu0fRosmd4FSaZsvWVhOtCEPivpsb2XF02-8TrKUHrB2iS8VsQ

### Register
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Yesser Miranda",
  "email": "miranda@yesserm.dev",
  "password": "password1234"
}

### Login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "miranda@yesserm.dev",
  "password": "password1234"
}

### Refresh access token
POST {{baseUrl}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Get profile
GET {{baseUrl}}/api/v1/users/me
Authorization: Bearer {{accessToken}}
Accept: application/json

### Get all users
GET {{baseUrl}}/api/v1/users
Authorization: Bearer {{accessToken}}
Accept: application/json
