@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZW1vQGV4YW1wbGUuY29tIiwiaWF0IjoxNzgzNDYzODUyLCJleHAiOjE3ODM0NjQ3NTJ9.AIstqJ5rWRur3ujanl_m0Zei7Pxo8Sd5uHJnC58YxQM
@refreshToken = uXeNyomF6xkdRQqmDPjxP_RfLI8aJotzo07OsQhyHjvLuOzWu9Q7FqPrMVDDzTaUT9KBG5Vcnot6DLfXJP-IWA

### Register
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Yesser Miranda",
  "email": "miranda@yesserm.dev",
  "password": "password1234"
}

### Login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "miranda@yesserm.dev",
  "password": "password1234"
}

### Refresh access token
POST {{baseUrl}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Get profile
GET {{baseUrl}}/api/v1/users/me
Authorization: Bearer {{accessToken}}
Accept: application/json

### Get all users
GET {{baseUrl}}/api/v1/users
Authorization: Bearer {{accessToken}}
Accept: application/json
