spring.application.name=demosb4

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

app.security.jwt.secret=V2h5VGhpcklzVGhpcklzVGhpcklzVGhpcklzVGhpcklzVGhpcklzVGhpcklz
app.security.jwt.access-token-expiration=900000
app.security.jwt.refresh-token-expiration=604800000
app.security.admin-setup-key=V2h5VGhpcklzVGhpcklzVGhpcklzVGhpcklzVGhpcklzVGhpcklzVGhpcklz

app.external-api.base-url=https://jsonplaceholder.typicode.com
