### Register user
POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "name": "Demo User",
  "email": "demo@example.com",
  "password": "password123"
}

### Login user
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "demo@example.com",
  "password": "password123"
}

### Refresh token
POST http://localhost:8081/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
