server.port=8080
spring.application.name=api-gateway

app.routes.auth-service-uri=${AUTH_SERVICE_URI:http://localhost:8081}
app.routes.user-service-uri=${USER_SERVICE_URI:http://localhost:8082}
app.routes.business-service-uri=${BUSINESS_SERVICE_URI:http://localhost:8083}
