server.port=8080
spring.application.name=api-gateway

app.routes.legacy-monolith-uri=${LEGACY_MONOLITH_URI:http://localhost:8085}
app.routes.auth-service-uri=${AUTH_SERVICE_URI:http://localhost:8081}
app.routes.user-service-uri=${USER_SERVICE_URI:http://localhost:8082}
