server.port=8081
spring.application.name=auth-service

spring.datasource.url=${AUTH_DATASOURCE_URL:jdbc:h2:mem:authdb}
spring.datasource.username=${AUTH_DATASOURCE_USERNAME:sa}
spring.datasource.password=${AUTH_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${AUTH_DATASOURCE_DRIVER:org.h2.Driver}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:900000}
app.security.jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
