server.port=8084
spring.application.name=catalog-service

spring.datasource.url=${CATALOG_DATASOURCE_URL:jdbc:h2:mem:catalogdb}
spring.datasource.username=${CATALOG_DATASOURCE_USERNAME:sa}
spring.datasource.password=${CATALOG_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${CATALOG_DATASOURCE_DRIVER:org.h2.Driver}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

springdoc.enable-data-rest=false
springdoc.enable-hateoas=false
