server.port=${LEGACY_MONOLITH_PORT:8085}
spring.application.name=demosb4

spring.datasource.url=${LEGACY_DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${LEGACY_DATASOURCE_USERNAME:sa}
spring.datasource.password=${LEGACY_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${LEGACY_DATASOURCE_DRIVER:org.h2.Driver}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
