server.port=8082
spring.application.name=user-service

spring.datasource.url=${USER_DATASOURCE_URL:jdbc:h2:mem:userdb}
spring.datasource.username=${USER_DATASOURCE_USERNAME:sa}
spring.datasource.password=${USER_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${USER_DATASOURCE_DRIVER:org.h2.Driver}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
