spring.application.name=api-gateway

server.port=8080

app.routes.legacy-monolith-uri=${LEGACY_MONOLITH_URI:http://localhost:8085}
app.routes.auth-service-uri=${AUTH_SERVICE_URI:http://localhost:8081}
app.routes.user-service-uri=${USER_SERVICE_URI:http://localhost:8082}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
