ALTER TABLE users ADD COLUMN created_by VARCHAR(150) NOT NULL DEFAULT 'system';
ALTER TABLE users ADD COLUMN updated_by VARCHAR(150) NOT NULL DEFAULT 'system';

ALTER TABLE roles ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE roles ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE roles ADD COLUMN created_by VARCHAR(150) NOT NULL DEFAULT 'system';
ALTER TABLE roles ADD COLUMN updated_by VARCHAR(150) NOT NULL DEFAULT 'system';

ALTER TABLE refresh_tokens ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE refresh_tokens ADD COLUMN created_by VARCHAR(150) NOT NULL DEFAULT 'system';
ALTER TABLE refresh_tokens ADD COLUMN updated_by VARCHAR(150) NOT NULL DEFAULT 'system';
